### PR TITLE
Feature/contact us

### PR DESCRIPTION
**Pull request by happimaker**

### CODE REVIEW

**Comment by tlpriest** [comment]
@computationalcore I noticed that when I run this with `npm start` and click submit, it does not actually submit the form to pipedream -- see the execution history https://pipedream.com/@bespoke-creations/skills-vue-p_A2CDJNg/edit?e=23sv7Xw5gEwhXNVjbE174CZUzsQ -- this could be an unclear requirement. Let us know what you think of this PR.

**Comment by happimaker** [comment]
@tlpriest You are talking to me? Have you tried to pull the latest?

**Comment by happimaker** [comment]
@tlpriest And also please make sure if you have set `env` file.
You can find it here just update the name as `.env`.
https://github.com/happimaker/skills-react/blob/feature/contact-us/.env.example

**Comment by tlpriest** [comment]
> @tlpriest And also please make sure if you have set `env` file. You can find it here just update the name as `.env`. https://github.com/happimaker/skills-react/blob/feature/contact-us/.env.example

That works.

**Comment by happimaker** [comment]
Sounds good. :)

**Pull request closed without merging**
